//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiTesting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiTesting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Dashboard.Resources.ApiTesting", typeof(ApiTesting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Testing.
        /// </summary>
        public static string ApiTestingHeader {
            get {
                return ResourceManager.GetString("ApiTestingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} API Testing.
        /// </summary>
        public static string ApiTestingPageTitle {
            get {
                return ResourceManager.GetString("ApiTestingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string ApiTestingRequestHeader {
            get {
                return ResourceManager.GetString("ApiTestingRequestHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string ApiTestingResponseHeader {
            get {
                return ResourceManager.GetString("ApiTestingResponseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL or path.
        /// </summary>
        public static string ApiTestingUrlPlaceholder {
            get {
                return ResourceManager.GetString("ApiTestingUrlPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ApiTestingSendButton {
            get {
                return ResourceManager.GetString("ApiTestingSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string ApiTestingHeadersTab {
            get {
                return ResourceManager.GetString("ApiTestingHeadersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string ApiTestingBodyTab {
            get {
                return ResourceManager.GetString("ApiTestingBodyTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header-Name: Header-Value (one per line).
        /// </summary>
        public static string ApiTestingHeadersPlaceholder {
            get {
                return ResourceManager.GetString("ApiTestingHeadersPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request body (JSON, XML, etc.).
        /// </summary>
        public static string ApiTestingBodyPlaceholder {
            get {
                return ResourceManager.GetString("ApiTestingBodyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ApiTestingStatus {
            get {
                return ResourceManager.GetString("ApiTestingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ApiTestingTime {
            get {
                return ResourceManager.GetString("ApiTestingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace ID.
        /// </summary>
        public static string ApiTestingTraceId {
            get {
                return ResourceManager.GetString("ApiTestingTraceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a resource to begin testing APIs.
        /// </summary>
        public static string ApiTestingEmptyState {
            get {
                return ResourceManager.GetString("ApiTestingEmptyState", resourceCulture);
            }
        }
    }
}
